
# ===============================
# Application
# ===============================
spring.application.name=MGW
server.port=8080

# ===============================
# Eureka Client
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===============================
# Spring Cloud Gateway
# ===============================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ===============================
# Security - Keycloak (JWT)
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/logistics-realm

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info

# ===============================
# Logs (optionnel)
# ===============================
logging.level.org.springframework.security=INFO
logging.level.org.springframework.cloud.gateway=INFO

